### ISSUE TITLE
Local development instructions aren't correct

### ISSUE THREAD

**Issue by EmlynC** [pydata/conf_site#106]
There are a few issues with the development documentation, ideally I should be able to plonk the commands into the terminal and get running without editing files. Namely:
1. `dev.py` is not functional out of the box because it relies on  `secrets.py` that does not include all the defaults for all variables to run.
2. `secrets.py` must be created by copying `secrets.example.py` to `secrets.py`
3. `local.py` must be created by copying `local.example.py` to `local.py`
4. `symposion_cms`, presumably an app, is listed in the `requirements/base.txt`, but the URL is broken `github.com/pydata/symposion.git@patched#egg=symposion`.

I suggest that all the variables imported from `secrets` are commented out, they don't appear necessary, but do correct me if I'm wrong. Rename `local.example.py` to `local.py` as it is harmless. Fix the URL for the `symposion_cms` requirement or delete the `cms.json` fixture if it's not necessary.

Doing the above allows the site to run on localhost.

**Comment by aterrel** [comment]
@EmlynC Thanks for taking the time to submit an issue! I will have to admit we have not prioritized making this repo a standalone app that could just be launched by anyone. There are probably many more gotchas along the way.  But if you have a patch for this I would be happy to review it.

**Comment by aterrel** [comment]
Opps I didn't see #107 and #108.

**Comment by EmlynC** [comment]
No worries Andy! FYI, I'm one of the committee members for PyData London. I kept #107 and #108 separate because it's easier to pull separately. As for `symposion_cms`, I'm not sure what the patched version included because I can't find the referenced file.

**Comment by aterrel** [comment]
@martey will have more details on that.

**Comment by martey** [comment]
The deployment documentation is horribly out of date - I did a poor job of updating it after I converted the deployment to use Ansible. I will try and get completely updated instructions up by the end of the week.

> As for symposion_cms, I'm not sure what the patched version included because I can't find the referenced file.

The symposion line in `requirements.txt` points to [the patched branch of pydata's symposion Github repository](https://github.com/pydata/symposion/tree/patched).

**Comment by EmlynC** [comment]
Nevermind @martey, documentation gets out-of-date :smile:, we're all guilty of it! 

The git link for `symposion` *does* work, my apologies. The following pip command does the same thing:

```bash
pip install git+git://github.com/pydata/symposion.git@patched
```

However, there still isn't a `symposion.cms` module. Incidentally, the authentication seems to require an authenticate method from TeamPermissionsBackend in symposion — probably best to add the standard ModelBackend to the local.py settings.

**Comment by narayanaditya95** [comment]
Seconded,

The app is not able to locate the `symposion_cms.page` module/model.
When loading fixtures from `fixtures.cms,json` the app complains:
```
django.core.serializers.base.DeserializationError: Problem installing fixture '/Users/aditn/pydata/conf_site/fixtures/cms.json': Invalid model identifier: 'symposion_cms.page'
```
