### ISSUE TITLE
how are static assets compiled in a production environment?

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#30]
I do not know how to compile static assets in production, thus I was not able to add a fabric command to handle this for deployments. This needs to be added to the fabfile.py and documented. The current site has some static assets being used on the seattle2015 landing page that are not checked in to this repo, and I do not know how they were deployed. This needs to be figured out for #37.

**Comment by danrjohnson** [comment]
This looks like they were checked out from https://github.com/pydata/pydata-seattle directly into the public folder post setup.

Is this the way we want to continue to deploy these (if so I can add a step to do so) or do we want to move the relevant stuff into this repo instead?

**Comment by codersquid** [comment]
I would rather see relevant stuff moved to this repo.

**Comment by danrjohnson** [comment]
Moved this media into repo, issued PR.  Also fixed nginx locations for static/uploaded media
