### ISSUE TITLE
add registration button

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#33]
Add Seattle Eventbrite link to the landing page. The URL is:  https://www.eventbrite.com/e/pydata-seattle-2015-tickets-16360608019

The registration button from Dallas doesn't work since the Dallas page uses Bootstrap. It looks like this if you try to imitate it.

![register](https://cloud.githubusercontent.com/assets/529748/6888261/0765ef58-d63e-11e4-9284-7706370b4c1b.png)

I tested in in production because everything is chaos right now. Here's the merge with the button added. It is no longer in production. #32

**Comment by codersquid** [comment]
I went ahead and just added a text link for now under the date.

**Comment by lsilen** [comment]
Thanks Sheila. Here's the code from Eventbrite for the button. 
<a href="http://www.eventbrite.com/e/pydata-seattle-2015-tickets-16360608019?ref=ebtnebregn" target="_blank"><img src="https://www.eventbrite.com/custombutton?eid=16360608019" alt="Eventbrite - PyData Seattle 2015" /></a>

**Comment by codersquid** [comment]
this was fixed in https://github.com/pydata/conf_site/commit/afc9015a724482bf823e1d25dc5b8b22b6137308
