### ISSUE TITLE
stabilize production deployments

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#37]
The current production environment was set up manually. This issue tracks the work of setting up a production environment that works with an automated deployment process so that we can push and rollback changes easily.

I've used fabric to deploy the site with vagrant as well as to a live box that was set up for me. confsite.pydata.org. I have not used it to do anything with the current production box.

- [x] review the fab stuff
- [ ] set up production and staging instances
- [ ] direct conf.pydata.org/seattle2015 traffic to new production instance 
- [ ] migrate all the data from conf.pydata.org/seattle2015 to the new site.

**Comment by danrjohnson** [comment]
@codersquid 

I've reviewed the fabric script and a couple small updates in https://github.com/pydata/conf_site/pull/39 .  I need to see about getting access to create new server to deploy this to, but Vagrant is deploying correctly out of box.

**Comment by codersquid** [comment]
@danrjohnson do you have access to confsite.pydata.org?

**Comment by danrjohnson** [comment]
@codersquid it does not appear so.

Also, I'll need some access to create a new box to replace confsite when the time comes.

**Comment by codersquid** [comment]
Hi @tpowellcio is it possible to give @danrjohnson and a few other people access to the rackspace account with enough privs to create new servers? If not, turn this ticket back over to @danrjohnson so he can specify the type of server he'd like.

**Comment by danrjohnson** [comment]
New site setup @ http://104.239.175.74/seattle2015/.  

I temporarily added the ip address to allowed hosts for this server and we can clone this server when we decide to setup a staging server.

Need to coordinate content and data migration.

**Comment by codersquid** [comment]
@tpowellcio could we have seattle.pydata.org point to 104.239.175.74?

**Comment by codersquid** [comment]
:+1: on the subdomain resolving.

**Comment by codersquid** [comment]
Jeff suggested opening separate issues versus having a task list. Since we have this working to deploy things to the new server, I'll consider this done and close it.
