### ISSUE TITLE
Internet Explorer problems

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#38]
This is the only detail I have. From email: When you click on PyData Seattle the link crashes Internet Explorer.

**Comment by codersquid** [comment]
I don't have a way to reproduce this issue at the moment. I had a friend try and reproduce it from a windows box running IE 11.0.9600 or 11.0.17 and he couldn't get it to crash.

**Comment by tpowellcio** [comment]
You can test using https://www.modern.ie/en-us or http://www.browserstack.com/screenshots

**Comment by tpowellcio** [comment]
I was able to reproduce it on Windows 7 x64 IE 11.09600
![screen shot 2015-04-02 at 20 44 37](https://cloud.githubusercontent.com/assets/649601/6976989/48afe7b4-d979-11e4-922c-6ac787457729.png)
![screen shot 2015-04-02 at 20 44 06](https://cloud.githubusercontent.com/assets/649601/6976988/48aecbe0-d979-11e4-863e-b814668c0fc0.png)

**Comment by tpowellcio** [comment]
Only happens when I click on the link, but works find when I go directly to http://conf.pydata.org/seattle2015/

**Comment by codersquid** [comment]
I had a friend online reproduce a crash with version 11.0.9600.17689, faulting module as "MSHTML.dll". I am unable to run the vm I downloaded -- it freezes up my linux laptop. I tried reproducing it by signing up for a MS live account and connecting to a test IE app remotely, but it works fine and doesn't fail.

Does only the Seattle link fail? It has the same style as the other event links.

**Comment by codersquid** [comment]
@tpowellcio can I close this issue out now that you've landed https://github.com/pydata/conference/pull/59 ?

**Comment by tpowellcio** [comment]
Yes I fixed it by inserting into the page head:
 ```
<meta http-equiv="X-UA-Compatible" content="IE=9">
```

Closing issue.
