### ISSUE TITLE
CFP is returning Page not Found

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#41]
reported in email

> Apparently when people search google for Seattle PyData, the con.pydata.org comes up second and third. When someone tries to click on the CFP link they get a “Page not Found” message.
>
> If the site needs to be up, can we link it to the same CFP the other one is going to?

**Comment by codersquid** [comment]
If you get to the dashboard without being logged in and click the "CFP" link you end with a url that looks something like this. I've clicked it multiple times to have a particulrly weird example:

http://conf.pydata.org/seattle2015/account/signup/cms_page/cms_page/cms_page/

**Comment by codersquid** [comment]
and it's likely due to some thing incorrect in how the sitetree for CFP is defined. I'm investigating.

**Comment by codersquid** [comment]
should be working now. http://conf.pydata.org/seattle2015/cfp/

**Comment by lsilen** [comment]
Thanks, I think they were doing exactly that, clicking on CFP without being logged in and then getting the Page not Found. User error :)

I think this (conf.pydata.org) is also where they are getting the 404 for PyData Dallas. Berlin is not even up on this site. This is the one we’ll be using moving forward, correct. It would be great to not have both live.

 
> On Apr 7, 2015, at 5:31 PM, Sheila Miguez <notifications@github.com> wrote:
> 
> should be working now. http://conf.pydata.org/seattle2015/cfp/ <http://conf.pydata.org/seattle2015/cfp/>
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/41#issuecomment-90749787>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by codersquid** [comment]
@lsilen I opened this issue for that https://github.com/pydata/conference/issues/63

I need a little more background on the plans for pydata.org, conf.pydata.org. I'll post to the mailing list.
