### ISSUE TITLE
PyData London site

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#47]
Deploy a PyData London site. It can have a landing page like the Seattle site that links to a symposion instance. At some point we'll probably have a cookiecutter-esque repo for this type of thing, but for now we don't. One brute force approach is to fork this repo to pydata/london2015 and do some search replace.

**Comment by danrjohnson** [comment]
This is up at http://104.130.6.68/ .  Everything that isn't the root, will redirect to root.  I'm unsure of what sponsor's should or should not be there.  Need feedback about this.

**Comment by codersquid** [comment]
@lsilen I'm not sure who the sponsors are.

@tpowellcio could we have london.pydata.org for 104.130.6.68 ?

**Comment by lsilen** [comment]
We only need Continuum and Bloomberg on right now.


> On Apr 17, 2015, at 3:48 PM, Sheila Miguez <notifications@github.com> wrote:
> 
> @lsilen <https://github.com/lsilen> I'm not sure who the sponsors are.
> 
> @tpowellcio <https://github.com/tpowellcio> could we have london.pydata.org for 104.130.6.68 ?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/47#issuecomment-94072186>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by danrjohnson** [comment]
Updated.

**Comment by codersquid** [comment]
http://london.pydata.org/ is resolving now.

thanks!
