### ISSUE TITLE
Cannot create tutorial (jupytercon branch)

### ISSUE THREAD

**Issue by maartenbreddels** [pydata/conf_site#473]
Hi Martey,

I found an issue adding a tutorial:
```
column "target_audience" of relation "proposals_proposal" does not exist
LINE 1: ...oposal" ("proposalbase_ptr_id", "audience_level", "target_au...
```

or a screenshot:
![image](https://user-images.githubusercontent.com/1765949/76619048-4a6e5d00-652a-11ea-82dc-28780efbfb9c.png)

**Comment by maartenbreddels** [comment]
The same happens when I submit a new talk.

**Comment by martey** [comment]
This error should go away if you apply the database migrations in #471:

> DJANGO_SETTINGS_MODULE="conf_site.settings.production" ./manage.py migrate
