### ISSUE TITLE
notification message has text of href rather than actual link

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#49]
Navigating to the submission page causes a message to print for users who have not created a speaker profile.

The message is

> To submit a proposal, please <a href='/seattle2015/account/login/'>log in</a> and create a speaker profile via the dashboard.

I'm not sure why it happens like that. I've looked at the template and it is using {% url "blahblahblah

**Comment by danrjohnson** [comment]
Looking at that template, its actually different text than what is being displayed there.  Digging further.

**Comment by danrjohnson** [comment]
This text is coming through the message framework 

        messages.info(request, "To submit a proposal, please "
                      "<a href='{0}'>log in</a> and create a speaker profile "
                      "via the dashboard.".format(settings.LOGIN_URL))

And looks like it isn't escaped when rendered in the template.

I fixed this by overriding messages template to mark message text as safe.
