### ISSUE TITLE
Design theming

### ISSUE THREAD

**Issue by jeffsedik** [pydata/conf_site#50]
Convert design to bootstrap and then make that design a theme. Estimate for work, 8 to 16 hours.

**Comment by furiousdave** [comment]
This work (commit https://github.com/pydata/conf_site/commit/7df54fdc569f9b9688eeb9c5039853f0e774a4a1) is up at seattle.pydata.org

The majority of hardcoded seattle2015 references have been removed from the code. Homepage content is now in a box. Sponsors in the sidebar now pull from the sponsors app. I added the existing 3 and set them at 'supporting' level for the time being. Created and added favicons. I tried to make the nav pretty close to the Berlin site, visually.
