### ISSUE TITLE
Remove subdirectories from url patterns?

### ISSUE THREAD

**Issue by furiousdave** [pydata/conf_site#51]
@codersquid 

If these conference sites are to be accessed at subdomains moving forward, it probably makes sense to remove all the seattle2015 paths from the urls patterns and further move toward making this code reusable. I can do that, just want to make sure there's no reason to keep them first.

https://github.com/pydata/conf_site/blob/master/conf_site/urls.py

**Comment by codersquid** [comment]
It totally makes sense to clean up the urls.py. I didn't want to change anything right when everyone was furiously busy, so I didn't.

I haven't fully thought through the implications of using subdomains. It might be an antipattern. but, we could have <location>.pydata.org/<yyyyy>. which I see other events use.

**Comment by furiousdave** [comment]
This is complete
https://github.com/pydata/conf_site/commit/c655d4f432ba515903985d2cfc1a3f8b07a458fc
