### ISSUE TITLE
London image sizing

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#52]
The London image is a bit large and should be closer in size to the Seattle image.

**Comment by jeffsedik** [comment]
Sheila, the images are two different aspect ratios. Changing the London image to match the height of the Seattle image looks odd. Do you want to provide a cropped version of the London image for us to use? if not, please suggest a width we should use for the current London image.

**Comment by codersquid** [comment]
@jeffsedik I don't have that. @lsilen do you have what @jeffsedik needs?

**Comment by jeffsedik** [comment]
![london](https://cloud.githubusercontent.com/assets/11822679/7431701/e00b799c-efe6-11e4-9832-de034c070c67.png)

Dan, please replace the london image with the attached.

**Comment by jeffsedik** [comment]
![london](https://cloud.githubusercontent.com/assets/11822679/7431736/2cc9eb88-efe7-11e4-8e2e-b0ff9c308cf8.jpg)

Dan, please replace the london image with the attached.

**Comment by lsilen** [comment]
Does that image work?


> On May 1, 2015, at 9:48 AM, jeffsedik <notifications@github.com> wrote:
> 
>  <https://cloud.githubusercontent.com/assets/11822679/7431736/2cc9eb88-efe7-11e4-8e2e-b0ff9c308cf8.jpg>
> Dan, please replace the london image with the attached.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/52#issuecomment-98147383>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by jeffsedik** [comment]
I think it does. It's in place on http://london.pydata.org/

**Comment by lsilen** [comment]
Looks much better! Is the CFP live? I’m meeting with them in 4 minutes. and wanted to give an update.


> On May 1, 2015, at 12:16 PM, jeffsedik <notifications@github.com> wrote:
> 
> I think it does. It's in place on http://london.pydata.org/ <http://london.pydata.org/>
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/52#issuecomment-98180520>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by furiousdave** [comment]
The CFP should now be up

**Comment by lsilen** [comment]
Sites are looking great!! It’s just a matter of getting the CFP off of the homepages now.


> On May 1, 2015, at 12:56 PM, furiousdave <notifications@github.com> wrote:
> 
> The CFP should now be up
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/52#issuecomment-98187902>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by jeffsedik** [comment]
What text content should appear on the home page? Just this?

PyData London 2015
June 19-21
Hosted by Bloomberg

**Comment by jeffsedik** [comment]
@lsilen - Following up on my comment. Please let me know what text content should appear on the London home page and we'll make the adjustments. Thanks!

**Comment by martey** [comment]
Closing, since the London 2015 conference was four years ago, so this is no longer a valid issue.
