### ISSUE TITLE
London CFP

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#53]
Change "Call for Proposals" text to below:

Call for Proposals

Proposals for PyData London 2015 will be accepted 27 April – 18 May. The event brings together analysts, scientists developers, engineers, architects and others from the Python data science community to discuss new techniques and tools for management, analytics and visualization of data. Presentation content can be at a novice, intermediate or advanced level. Talks will run 30-40 min and hands-on tutorials will run 90-120 min.

**Comment by danrjohnson** [comment]
I've made the requested change.
