### ISSUE TITLE
fix admin error emails

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#54]
The emails are going to Amenity. We should set up a different address for them. Feel free to put me on the list of admins.

Also, is there any reason to show errors for invalid http host headers? If not, then we should disable emails for that type of error.

**Comment by lsilen** [comment]
I just took her off web@pydata.org.

> On Apr 21, 2015, at 3:51 PM, Sheila Miguez <notifications@github.com> wrote:
> 
> The emails are going to Amenity. We should set up a different address for them. Feel free to put me on the list of admins.
> 
> Also, is there any reason to show errors for invalid http host headers? If not, then we should disable emails for that type of error.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/54>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by martey** [comment]
This was obsoleted by #252. Errors now go to Sentry. Anyone who needs access to error information should feel free to contact me.
