### ISSUE TITLE
seattle site tweaks

### ISSUE THREAD

**Issue by jeffsedik** [pydata/conf_site#56]
On the Homepage, the CFP text needs to be removed if the CFP tab is working. It should have the news/blog post on it and a brief description of PyData. I think this was on Amenity’s design.

On the Sponsor pull-down “Sponsors” logos are not showing up, is that because they have to be added in admin?

For Apply to be a sponsor, I think it would be helpful to see the information on Becoming a Sponsor, e.g. the levels and costs without having to register or apply to be a sponsor. Should that be another pull-down. This has been on all the past sites.

Dato logo is too large. Are all the logos set to be the same size or is it based on level?

**Comment by furiousdave** [comment]
1. On hold waiting to see this design comp.

2. The sponsor images now appear on http://seattle.pydata.org/sponsors/

3. There is a page which is linked to from /sponsors/, http://seattle.pydata.org/sponsors/prospectus/.  This could be added to the top nav along with any other menu changes via the sitetree app in the admin, http://seattle.pydata.org/admin/sitetree/tree/1/. Should the top menu maybe have a link to the above page with the text 'Become a Sponsor' and then the 'Apply to be a Sponsor' link be moved from the top menu onto that info page?

4. Currently, the logos are all just set to have a max-width of the size of the column (~300px at max resolution). We can obviously change the logic of that or separate them by level, just need some direction on what needs to be done. Feel free to assign the correct levels to the sponsors as they're currently all set to 'supporting', http://seattle.pydata.org/admin/symposion_sponsorship/sponsor/

**Comment by lsilen** [comment]
2. The sponsor logos also need to be on the homepage. In a side bar? 
Will this page include the sponsor's company description? Continuum will always be on the sponsor list as the Founding Sponsor, but this isn't a level others can sponsor at. How can that be made to show up? I tried to add it but it won't show up in the correct order - it should be first , but because there isn't a dollar amount associated with it, it's last. It shouldn't be on the application page.

3. When the link is clicked would they be taken to the sponsor page on pydata.org? Would we be able to change the info from the admin? Maybe the menu could have "Sponsor Information" and "Apply to be a Sponsor"

**Comment by furiousdave** [comment]
@lsilen 
Let me know if you're able to locate this seattle homepage design for my reference.

I changed the order field of the Founding level to -1. It now displays first. There is currently no elegant way, however, to keep it out of the dropdown on http://seattle.pydata.org/sponsors/apply/. If we forked symposion, we could perhaps add a checkbox to allow disabling it in the admin. A clunkier but much quicker and less involved solution is I could just remove that option from the application form field with javascript. Let me know how you'd like to proceed with this.

The "Sponsor Prospectus" page is fully editable here, http://seattle.pydata.org/admin/symposion_cms/page/9/

I changed the site tree menu title of Sponsors to Sponsor Information, http://seattle.pydata.org/admin/sitetree/tree/1/item_6/

**Comment by jeffsedik** [comment]
@lsilen
Any additional work for Dave to do on this issue? Or can I resolve it?

**Comment by lsilen** [comment]
Sorry, just now seeing this. I think the option of removing the option from the application form field with javascript sounds great. Would that have to be done for each site though, Seattle and London and then each new site moving forward?

**Comment by martey** [comment]
Closing since the issues listed here are no longer applicable.
