### ISSUE TITLE
CFP site tweaks for JupyterCon

### ISSUE THREAD

**Issue by jasongrout** [pydata/conf_site#565]
- [x] We should ask for the user's timezone during the conference for scheduling purposes. This is not part of the review, but also is not optional, so perhaps down at the bottom with the GDPR checkboxes? Do you have a good way to get a field for a timezone? If it will take a while to add, we'll just ask people later, since really this is just a proxy for asking when a good time to schedule live things with them is.
- Several of the questions should have wording tweaked for an online conference:
  - [x] **Brief Summary** "this will be in the public printed program." -> delete word "printed"
  - [x] `Do you have specific accessibility needs at the conference? Examples include, but not limited to: sign language, closed captioning, mobility, parent room, diet, etc.` -> closed captioning is the only one that makes sense now to me. @reshamas - are there other accessibility needs we should specifically list?
  - [x] I don't know that we need to collect the phone number anymore for "last-minute schedule changes". Does anyone oppose removing the question asking for the proposer's phone number?
- [x] The Sponsorship section of the dashboard points to PyData sponsorship materials. Either we should delete it or make it relevant to JupyterCon. On the registration site, we say:
  > Interested in Sponsoring? Email us at jupytercon-sponsor@numfocus.org to receive a prospectus.
- [x] The orange plain text is light and hard to read against the white background (not enough contrast). @martey suggested using the darker orange from the JupyterCon website and making the buttons black text/outline.

**Comment by martey** [comment]
> The orange plain text is light and hard to read against the white background (not enough contrast). @martey suggested using the darker orange from the JupyterCon website and making the buttons black text/outline.

The link and button color changes have been applied in https://github.com/pydata/conf_site/pull/566 and are live on the CFP site.

> We should ask for the user's timezone during the conference for scheduling purposes.

Since this is user-specific and not proposal-specific, I think this might make more sense if it was part of the "speaker profile" that submitters have to create before they are allowed to submit a proposal.

**Comment by jasongrout** [comment]
> Since this is user-specific and not proposal-specific, I think this might make more sense if it was part of the "speaker profile" that submitters have to create before they are allowed to submit a proposal.

Ah yes, good point.

**Comment by trallard** [comment]
Adding here the changes that need to be made to the tutorial submission form:

>Please describe what portion of your tutorial you plan to spend on student exercises, lecture, or other activities. 

Please describe what portion of the tutorial will be spent on the video presentation, hands-on exercises and self-assessment or knowledge checks (if any). This does not have to be laid minute-by-minute but give an overall idea on how the 3 hours will be distributed. 

> Please summarize your teaching or public speaking experience, as well as your experience with the subject of the tutorial.

Please summarize your teaching or public speaking experience, as well as your experience with the subject of the tutorial. Also, indicate if you have prior experience creating online or recorded content.

> Let us know if you have specific needs or special requests — for example, requests that involve accessibility, audio, or restrictions on when your proposal can be scheduled. We will be providing appropriate seating for attendees, a projector, and a microphone for you.

Let us know if you have specific requests or needs - for example, restrictions on when your virtual office hours can be scheduled and if you anticipate any issues recording your content. 

> Do you have specific​ accessibility needs at the conference​?
Examples include, but not limited to: sign language, closed captioning, mobility, parent room, diet, etc. Please indicate the specific need so we can plan in advance.

Do you have specific​ accessibility needs at the online conference​?
Examples include, but not limited to: closed captioning, need assistance with recording (note we can't promise to be able to help everyone with this, but we are still planning our speaker pack and should get back with more details).

**Comment by reshamas** [comment]
CURRENT
Do you have specific accessibility needs at the conference? Examples include, but not limited to: sign language, closed captioning, mobility, parent room, diet, etc. 

CHANGE TO:
Do you have specific accessibility needs at the conference? Examples include, but not limited to: sign language, closed captioning, ~mobility, parent room, diet,~ etc.

**Comment by jasongrout** [comment]
@reshamas - notice that @trallard suggested above "need assistance with recording" as well.

**Comment by reshamas** [comment]
@jasongrout sure, we can add that wherever it is applicable.

**Comment by reshamas** [comment]
@jasongrout I think it's fine to remove the phone number.  We asked for it in case of an emergency.  Since this is not an in-person event, it's less relevant and critical.

**Comment by martey** [comment]
I think the outstanding items in this issue have been changed. Please let me know if I missed anything, or if any additional changes should be made.
