### ISSUE TITLE
add me to london site

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#58]
- [x] Give my django user staff and superuser, shekay@pobox.com
- [x] Add my [ssh key](https://launchpad.net/~codersquid/+sshkeys) to the server account that admins the website, and/or add a user for me.

**Comment by jeffsedik** [comment]
@danrjohnson 
Please also give lsilen admin access.

**Comment by lsilen** [comment]
Can this happen now, I’ve got a lot of folks in London very upset with me!

> On May 12, 2015, at 9:00 AM, jeffsedik <notifications@github.com> wrote:
> 
> @danrjohnson <https://github.com/danrjohnson> 
> Please also give lsilen admin access.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/58#issuecomment-101293845>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by jeffsedik** [comment]
Should happen shortly. At the top of Dan's list for today.

**Comment by jeffsedik** [comment]
@lsilen 
What's the email address associated with your user name on the London site? We can't fine a user that uses leah@numfocus.org.

**Comment by danrjohnson** [comment]
@codersquid I setup an account for you and added keys in question to authorized keys.  You should have to set a password upon login.  Username is sheila

**Comment by codersquid** [comment]
@jeffsedik I bet it's her pydata.org address. I went ahead and added her.

**Comment by lsilen** [comment]
yes, leah@pydata.org

**Comment by lsilen** [comment]
THANKS

> On May 12, 2015, at 10:57 AM, Sheila Miguez <notifications@github.com> wrote:
> 
> @jeffsedik <https://github.com/jeffsedik> I bet it's her pydata.org address. I went ahead and added her.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/58#issuecomment-101330027>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449
