### ISSUE TITLE
sponsor logo not showing up

### ISSUE THREAD

**Issue by lsilen** [pydata/conf_site#61]
I added eScience Institute as a Silver Sponsor and added their logo under web logo. It's a .png but it's not showing up. http://seattle.pydata.org/

**Comment by danrjohnson** [comment]
There was a permissions problem on that file.  I changed the permissions manually and it displays now.  I'll have to look into why it was assigned the permissions it was at some point if this becomes a recurring problem.

**Comment by lsilen** [comment]
Thanks!

> On May 13, 2015, at 12:34 PM, Dan Johnson <notifications@github.com> wrote:
> 
> There was a permissions problem on that file. I changed the permissions manually and it displays now. I'll have to look into why it was assigned the permissions it was at some point if this becomes a recurring problem.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/61#issuecomment-101754372>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449
