### ISSUE TITLE
Sponsor logos too large on side bar

### ISSUE THREAD

**Issue by lsilen** [pydata/conf_site#62]
I know it was discussed that the logos may need to be resized. I need to add another and I think they are too large. Can they be reduced a little? Can this be done in admin?

**Comment by lsilen** [comment]
We just added Intel and it's huge, larger than Microsoft and Continuum which are larger sponsors. Can we make these smaller?  They can be sized according to their level if that's easier.

**Comment by martey** [comment]
Closing this since it is not relevant on current conference sites (we no longer display sponsors in the sidebar, and the images in the sponsors homepage section and sponsors page are automatically constrained).
