### ISSUE TITLE
Issue on london.pydata.org/speaker/profile/

### ISSUE THREAD

**Issue by jeffsedik** [pydata/conf_site#63]
@danrjohnson - please take a look at this.

---------- Forwarded message ----------
From: Leah Silen leah@numfocus.org
Date: Tue, May 19, 2015 at 10:28 AM
Subject: Fwd: Bug in london.pydata.org/speaker/profile/
To: sheila miguez shekay@pobox.com
Cc: Jeff Sedik jeff@imagescape.com

I checked and we did receive his proposal.

> Begin forwarded message:
> 
> From: Leonardo De Marchi demarchileonardo@gmail.com
> Subject: Bug in london.pydata.org/speaker/profile/
> Date: May 19, 2015 at 7:11:45 AM CDT
> To: admin@pydata.org
> 
> Hi,
> 
> I submitted a proposal for pydata London, using the email  demarchileonardo@gmail.com, but when I click on my email I get a "page not found error".
> 
> I've created a profile and submitted a proposal two weeks ago. Is there  aproblem?
> 
> thanks
> 
> Leo
> 
> L. D. M.
> 
> To unsubscribe from this group and stop receiving emails from it, send an email to admin+unsubscribe@pydata.org.

**Comment by jeffsedik** [comment]
![pydata error](https://cloud.githubusercontent.com/assets/11822679/7709043/c6f0382a-fe1f-11e4-83dc-fc7d51e0fded.png)

**Comment by danrjohnson** [comment]
Fixed in fb9208c0de8cd38f2ec7b190edfdb472cd1278e7

**Comment by jeffsedik** [comment]
@lsilen 
Please confirm with the user that this has been fixed, and I'll close this issue.

**Comment by martey** [comment]
Closing because of age.
