### ISSUE TITLE
Sponsor Info. on website

### ISSUE THREAD

**Issue by lsilen** [pydata/conf_site#64]
I've had several potential sponsors tell me they can't find any information regarding sponsorship levels on the Seattle and London sites. I thought we had discussed creating an additional item on the pull-down titled "Become a Sponsor" linked to http://pydata.org/sponsor/info/. Can this be added as soon as possible?   

Thanks.

**Comment by aterrel** [comment]
Added text to http://london.pydata.org/sponsors/apply/ .

Lowering priority

**Comment by martey** [comment]
The "Become a Sponsor" link on current conference sites links to the main sponsor prospectus on pydata.org, so this is no longer an issue.
