### ISSUE TITLE
Scheduled items repeating.

### ISSUE THREAD

**Issue by lsilen** [pydata/conf_site#65]
Jeff and I discussed during our call the fact that items such as; registration, breakfast, lunch, keynotes, etc. have to be entered as a presentation and will therefore show up on the schedule as the same item repeated on each slot at each time. So, for the 9:00 - 9:50 slot, Keynote will appear 3 times for the General Session and 4 times for Tutorials.

I think this is going to look bad when we have multiple items on 3 schedules repeated. I noticed on the PyCon site this isn’t the case and on the SciPy 2014 site these types of items are only listed in the first slot. I’m not sure if that would be easier. 

We will be creating the Seattle schedule tomorrow morning and I need to find a solution.

**Comment by jeffsedik** [comment]
@lsilen
Do you have admin access to the PyCon site and/or ScPy 2014? Using their method sounds like a great alternative to me but I don't have access to those sites so I'm not sure how they did it.

**Comment by lsilen** [comment]
No, I don’t. 

@codersquid - Do you know anyone that might have access?


> On May 21, 2015, at 9:05 AM, jeffsedik <notifications@github.com> wrote:
> 
> @lsilen <https://github.com/lsilen>
> Do you have admin access to the PyCon site and/or ScPy 2014? Using their method sounds like a great alternative to me but I don't have access to those sites so I'm not sure how they did it.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/65#issuecomment-104287619>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by codersquid** [comment]
I helped with the SciPy2014 site last year, and it's no longer a django site because we used the method that previous pycon's used for generating static sites after the event is over.

The repos are still available, https://github.com/scipy-conference/symposion and https://github.com/scipy-conference/SciPy-2014 One big difference for the SciPy site is that it was kludged together from an old version of symposion which we eventually forked due to various problems. I can't remember everything we did, or how we handled the event spanning bits.

I can revisit it talk things over with @jeffsedik and crew if it helps. I'm a little swamped still.

To be honest, I would not consider this high priority yet. I think it is cosmetic. Higher priority would be anything that makes the site unusable, broken links, etc.

**Comment by lsilen** [comment]
@jeffsedik can you find anything on theses repos? Although this is cosmetic it’s still a high priority, we can see how the schedule looks this evening when we get it up, but I would like to find a solution so this isn’t a reoccurring problem on every schedule.


> On May 21, 2015, at 10:37 AM, Sheila Miguez <notifications@github.com> wrote:
> 
> I helped with the SciPy2014 site last year, and it's no longer a django site because we used the method that previous pycon's used for generating static sites after the event is over.
> 
> The repos are still available, https://github.com/scipy-conference/symposion <https://github.com/scipy-conference/symposion> and https://github.com/scipy-conference/SciPy-2014 <https://github.com/scipy-conference/SciPy-2014> One big difference for the SciPy site is that it was kludged together from an old version of symposion which we eventually forked due to various problems. I can't remember everything we did, or how we handled the event spanning bits.
> 
> I can revisit it talk things over with @jeffsedik <https://github.com/jeffsedik> and crew if it helps. I'm a little swamped still.
> 
> To be honest, I would not consider this high priority yet. I think it is cosmetic. Higher priority would be anything that makes the site unusable, broken links, etc.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/65#issuecomment-104322541>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by codersquid** [comment]
One of my goals has been to take what things we needed/wanted to fix in symposion that we discovered during SciPy 2014 and see about merging them back to the current symposion and/or symposion project template.

The schedule page is a major pain point.

I've seen other events make different templates that don't do a grid, like PyOhio (if I recall correctly).

**Comment by martey** [comment]
This has been resolved by overriding the text of schedule slots.
