### ISSUE TITLE
Schedule view not showing links to talks

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#68]
I haven't had time to dig in to this but maybe someone could pick it up if I don't get to it soon. The schedule view isn't showing talk titles or linking to them.

![weird_schedule](https://cloud.githubusercontent.com/assets/529748/7841050/c787ddb0-045f-11e5-85c3-af77106492a9.png)

**Comment by codersquid** [comment]
The lack of links is probably due to the hardcoded "talk" "tutorial" in the template here

https://github.com/pydata/conf_site/blob/master/conf_site/templates/schedule/_grid.html#L16

I think in the scipy repo we changed the model to have a property to use in the conditional, but can't remember exactly. I'll check in to it tonight. This part is trivial to fix, I think.

I'm not sure what is causes the table to render that way, however.

**Comment by codersquid** [comment]
This comment should fix the link display, https://github.com/pydata/conf_site/commit/5015bd4204f45e36bfb7b3088996a1130e1b2666

I'll deploy it later, unless someone reviews, merges, and deploys it before I get to it.

![gridfix](https://cloud.githubusercontent.com/assets/529748/7847511/85d0c326-0489-11e5-8a49-7824c09980e0.png)

**Comment by codersquid** [comment]
this is fixed and you can see the links on the seattle site by visiting http://seattle.pydata.org/schedule/

I'll not hook that up to the site nav unless it is acceptable.

**Comment by lsilen** [comment]
The links look good. Thanks @codersquid!

> On May 27, 2015, at 11:18 PM, Sheila Miguez <notifications@github.com> wrote:
> 
> this is fixed and you can see the links on the seattle site by visiting http://seattle.pydata.org/schedule/ <http://seattle.pydata.org/schedule/>
> I'll not hook that up to the site nav unless it is acceptable.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/68#issuecomment-106165761>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449
