### ISSUE TITLE
Would like a page that lists all the selected speakers

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#71]
There may already be a symposion view for this.

When we have a page like this, perhaps we could change the Schedule site nav to have an option to list the speakers.

Schedule
- General Sessions. this would go to http://seattle.pydata.org/schedule/general-sessions/list/
- Tutorials. this would go to http://seattle.pydata.org/schedule/general-sessions/list/
- Speakers. This would go to the new list page, or a symposion page if it already exists

**Comment by lsilen** [comment]
I think that’s a great idea. It makes it much easier to navigate.

> On May 28, 2015, at 2:49 PM, Sheila Miguez <notifications@github.com> wrote:
> 
> There may already be a symposion view for this.
> 
> When we have a page like this, perhaps we could change the Schedule site nav to have an option to list the speakers.
> 
> Schedule
> 
> General Sessions. this would go to http://seattle.pydata.org/schedule/general-sessions/list/ <http://seattle.pydata.org/schedule/general-sessions/list/>
> Tutorials. this would go to http://seattle.pydata.org/schedule/general-sessions/list/ <http://seattle.pydata.org/schedule/general-sessions/list/>
> Speakers. This would go to the new list page, or a symposion page if it already exists
> —
> Reply to this email directly or view it on GitHub <https://github.com/pydata/conf_site/issues/71>.
> 

---
Leah Silen
Executive Director
NumFOCUS <http://numfocus.org/>
leah@numfocus.org
512-222-5449

**Comment by martey** [comment]
This was fixed by #310.
