### ISSUE TITLE
display issue with times in schedule grids

### ISSUE THREAD

**Issue by codersquid** [pydata/conf_site#73]
The site.css for table.calendar th.time has a width attribute that is too small, thus the times are overlapping the cell borders. This needs to be fixed.

I'm not entirely certain how the site.css was generated. In the repo I see some less files and a compiled site.css, but I was not involved in doing that stuff. I'll dig around.

![time_cells](https://cloud.githubusercontent.com/assets/529748/7951685/6bedeccc-0970-11e5-917f-78b12997a469.png)

**Comment by furiousdave** [comment]
Sheila, if you look in the static/conf_site dir, there is a Makefile. If I remember correctly, after editing the less files, running the command 'make build' in that dir will compile the css file.

**Comment by codersquid** [comment]
@furiousdave thanks, I winged it and ran the make file to compile the css file.
