### ISSUE TITLE
Sponsor, Account and About tabs not working from Venue page on Pydata Seattle

### ISSUE THREAD

**Issue by aterrel** [pydata/conf_site#75]
Steps to reproduce:

- Go to http://seattle.pydata.org/venue/
- Click any dropdown tab

**Comment by Dr-G** [comment]
This bug is also happening on nyc2015.pydata.org

**Comment by aterrel** [comment]
seems fine on chrome for nyc. I don't have an admin account on seattle, but
you need to add a new line before the final </iframe>
