### ISSUE TITLE
add example secrets.py

### ISSUE THREAD

**Issue by aterrel** [pydata/conf_site#77]
Not sure what all needs to be in the secrets.py file.

**Comment by aterrel** [comment]
n/m found it under settings

**Comment by aterrel** [comment]
Actually looks like `settings/conf_site/settings.example.py` has the wrong format.

`secrets.DATABASES_DEFAULT` is required for the `settings/conf_site/production.py` use.

**Comment by martey** [comment]
Fixed by b625b0426a0b54ef8372b2cd107da7b721190e5b in #218.
