### ISSUE TITLE
Change mailchimp sign-up on NYC site to point to NumFOCUS mailchimp account

### ISSUE THREAD

**Issue by Dr-G** [pydata/conf_site#80]
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//numfocus.us9.list-manage.com/subscribe/post?u=c4bde6125a526b0fe180fdc3d&amp;id=f8e0d0361d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Subscribe to our mailing list</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_c4bde6125a526b0fe180fdc3d_f8e0d0361d" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

**Comment by aterrel** [comment]
I need more information (basically where the post goes), see the example we are using now. If you want me to dig around mailchimp, just add aterrel to the mailchimp account.

```html
<div id="mc_embed_signup">
    <form action="//pydata.us4.list-manage.com/subscribe/post?u=2d93c878c488c4fc88ec0a27a&amp;id=c3038a03b3" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="novalidate">
        <div id="mc_embed_signup_scroll">
          <h2>Subscribe to Receive {{ SITE_NAME }} Updates</h2>
            <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
            <div class="mc-field-group">
                <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span></label>
                <input aria-required="true" value="" name="EMAIL" class="required email" id="mce-EMAIL" type="email">
            </div>
            <div id="mce-responses" class="clear">
                <div class="response" id="mce-error-response" style="display:none"></div>
                <div class="response" id="mce-success-response" style="display:none"></div>
            </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;">
                <input name="b_2d93c878c488c4fc88ec0a27a_c3038a03b3" tabindex="-1" value="" type="text">
            </div>
            <div class="clear"><input value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" type="submit"></div>
        </div>
    </form>
</div>
```

**Comment by Dr-G** [comment]
I just invited your gmail to Mailchimp so you can get whatever you need.

**Comment by aterrel** [comment]
@Dr-G I need access to modify the lists. Currently I only have access to MailChimp campaigns at the moment.

**Comment by Dr-G** [comment]
Should be fixed now

**Comment by aterrel** [comment]
this is working now.
