### ISSUE TITLE
reset form gives wrong email

### ISSUE THREAD

**Issue by aterrel** [pydata/conf_site#81]
When submitting forgot password, we show the wrong email address see screenshot. I'm guess this is some detail with a symposion setting.

![screen shot 2015-08-19 at 10 29 40 am](https://cloud.githubusercontent.com/assets/30583/9360709/7a035052-465d-11e5-9a63-5a56ba962bfd.png)

**Comment by martey** [comment]
Should the email address be web@pydata.org, or is there a different email address that it should link to?

**Comment by aterrel** [comment]
I think web@pydata.org is good.
