### ISSUE TITLE
Cleanup london and seattle

### ISSUE THREAD

**Issue by aterrel** [pydata/conf_site#82]
- [ ] scrap london and seattle, 
- [ ] move static pages to pydata.org/<city>2015
- [ ] point dns to pydata.org with rewrite rule in nginx that directs them to the appropriate  pydata.org/<city>2015
- [ ] shut down boxes

**Comment by Dr-G** [comment]
Please also be sure to remove the newsletter sign-ups on both Seattle and London.

**Comment by aterrel** [comment]
@Dr-G that was completed in #79

**Comment by Dr-G** [comment]
Beautiful, thanks!
