### ISSUE TITLE
NYC2015 sponsor not appearing on site

### ISSUE THREAD

**Issue by Dr-G** [pydata/conf_site#83]
Bank of America is entered on the back end as a sponsor for NYC. However, the logo and name, etc. is not appearing anywhere on the site: http://nyc2015.pydata.org/ (See under "Sponsors")

**Comment by lsilen** [comment]
In admin instead of only having NYC on the conference pull-down, Seattle is there also. I discovered that the sponsors will show up if the sponsor level is set for Seattle instead of NYC.
