### ISSUE TITLE
Link past events urls to Seattle & London sites

### ISSUE THREAD

**Issue by Dr-G** [pydata/conf_site#84]
http://pydata.org/Seattle2015/
http://pydata.org/london2015

I created the old conferences on the events page but the urls need to be linked up to the old sites:
http://pydata.org/events/

**Comment by aterrel** [comment]
yeah this is dependent on #82

**Comment by Dr-G** [comment]
@martey we need to get this issue resolved ASAP. Thank you!

**Comment by martey** [comment]
Both of these sites have been made static and the links on http://pydata.org/events are working, so I am going to close both this issue and #82.
